/* =========================================================
   수릿(Surit) - 출장 수리 접수/진행 관리 플랫폼
   Oracle DDL  |  1조  |  2026.08
   ---------------------------------------------------------
   [ERDCloud 사용법]
   ERDCloud > 프로젝트 열기 > 좌측 상단 메뉴 > Import > SQL
   아래 CREATE TABLE ~ 제약조건 부분을 붙여넣으면
   테이블과 관계선이 자동 생성됩니다.
   (COMMENT ON / INSERT 구문은 Import 시 제외해도 됩니다)
   ========================================================= */


/* ---------- 초기화 (재실행 시에만 사용) ----------
DROP TABLE REPAIR_COMMENT CASCADE CONSTRAINTS;
DROP TABLE REPAIR_RESULT  CASCADE CONSTRAINTS;
DROP TABLE ASSIGNMENT     CASCADE CONSTRAINTS;
DROP TABLE REQUEST_IMG    CASCADE CONSTRAINTS;
DROP TABLE REQUEST        CASCADE CONSTRAINTS;
DROP TABLE ENGINEER       CASCADE CONSTRAINTS;
DROP TABLE CATEGORY       CASCADE CONSTRAINTS;
DROP TABLE MEMBER         CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_CATEGORY;
DROP SEQUENCE SEQ_ENGINEER;
DROP SEQUENCE SEQ_REQUEST;
DROP SEQUENCE SEQ_IMG;
DROP SEQUENCE SEQ_ASSIGN;
DROP SEQUENCE SEQ_RESULT;
DROP SEQUENCE SEQ_COMMENT;
-------------------------------------------------- */


/* =========================================================
   1. MEMBER  (회원)
   ========================================================= */
CREATE TABLE MEMBER (
    MEMBER_NO     NUMBER          NOT NULL,
    MEMBER_ID     VARCHAR2(30)    NOT NULL,
    MEMBER_PWD    VARCHAR2(200)   NOT NULL,
    MEMBER_NAME   VARCHAR2(30)    NOT NULL,
    PHONE         VARCHAR2(20),
    EMAIL         VARCHAR2(100),
    ADDRESS       VARCHAR2(300),
    MEMBER_ROLE   CHAR(1)         DEFAULT 'U' NOT NULL,
    ENROLL_DATE   DATE            DEFAULT SYSDATE NOT NULL,
    STATUS        CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_MEMBER      PRIMARY KEY (MEMBER_NO),
    CONSTRAINT UQ_MEMBER_ID   UNIQUE (MEMBER_ID),
    CONSTRAINT CK_MEMBER_ROLE CHECK (MEMBER_ROLE IN ('U', 'A')),
    CONSTRAINT CK_MEMBER_STAT CHECK (STATUS IN ('Y', 'N'))
);

COMMENT ON TABLE  MEMBER              IS '회원';
COMMENT ON COLUMN MEMBER.MEMBER_NO    IS '회원번호 (PK)';
COMMENT ON COLUMN MEMBER.MEMBER_ID    IS '로그인 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD   IS '비밀번호 (암호화 저장)';
COMMENT ON COLUMN MEMBER.MEMBER_ROLE  IS '권한 U:일반회원 / A:관리자';
COMMENT ON COLUMN MEMBER.STATUS       IS 'Y:활성 / N:탈퇴';


/* =========================================================
   2. CATEGORY  (수리 카테고리)
   ========================================================= */
CREATE TABLE CATEGORY (
    CATEGORY_NO    NUMBER         NOT NULL,
    CATEGORY_NAME  VARCHAR2(30)   NOT NULL,
    CONSTRAINT PK_CATEGORY   PRIMARY KEY (CATEGORY_NO),
    CONSTRAINT UQ_CATEGORY   UNIQUE (CATEGORY_NAME)
);

COMMENT ON TABLE  CATEGORY               IS '수리 카테고리';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '냉장고 / 세탁기 / 에어컨 / 보일러 / TV / 인터넷 등';


/* =========================================================
   3. ENGINEER  (수리기사)
   ========================================================= */
CREATE TABLE ENGINEER (
    ENGINEER_NO      NUMBER        NOT NULL,
    ENGINEER_NAME    VARCHAR2(30)  NOT NULL,
    CATEGORY_NO      NUMBER        NOT NULL,
    PHONE            VARCHAR2(20),
    REGION           VARCHAR2(50),
    ENGINEER_STATUS  CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_ENGINEER     PRIMARY KEY (ENGINEER_NO),
    CONSTRAINT FK_ENG_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY (CATEGORY_NO),
    CONSTRAINT CK_ENG_STATUS   CHECK (ENGINEER_STATUS IN ('Y', 'N'))
);

COMMENT ON TABLE  ENGINEER                 IS '수리기사';
COMMENT ON COLUMN ENGINEER.CATEGORY_NO     IS '담당 카테고리 (FK)';
COMMENT ON COLUMN ENGINEER.REGION          IS '담당 지역';
COMMENT ON COLUMN ENGINEER.ENGINEER_STATUS IS 'Y:배정가능 / N:휴무';


/* =========================================================
   4. REQUEST  (수리 접수)  ★ 핵심 테이블
   ========================================================= */
CREATE TABLE REQUEST (
    REQUEST_NO       NUMBER          NOT NULL,
    MEMBER_NO        NUMBER          NOT NULL,
    CATEGORY_NO      NUMBER          NOT NULL,
    REQUEST_TITLE    VARCHAR2(100)   NOT NULL,
    PRODUCT_NAME     VARCHAR2(100),
    SYMPTOM          VARCHAR2(2000)  NOT NULL,
    VISIT_ADDRESS    VARCHAR2(300)   NOT NULL,
    VISIT_HOPE_DATE  DATE,
    REQUEST_STATUS   VARCHAR2(20)    DEFAULT '접수완료' NOT NULL,
    READ_COUNT       NUMBER          DEFAULT 0 NOT NULL,
    CREATE_DATE      DATE            DEFAULT SYSDATE NOT NULL,
    STATUS           CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_REQUEST     PRIMARY KEY (REQUEST_NO),
    CONSTRAINT FK_REQ_MEMBER  FOREIGN KEY (MEMBER_NO)   REFERENCES MEMBER (MEMBER_NO),
    CONSTRAINT FK_REQ_CATE    FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY (CATEGORY_NO),
    CONSTRAINT CK_REQ_STATUS  CHECK (REQUEST_STATUS IN ('접수완료', '기사배정', '방문예정', '처리완료', '취소')),
    CONSTRAINT CK_REQ_DEL     CHECK (STATUS IN ('Y', 'N'))
);

COMMENT ON TABLE  REQUEST                 IS '수리 접수';
COMMENT ON COLUMN REQUEST.SYMPTOM         IS '고장 증상 설명';
COMMENT ON COLUMN REQUEST.VISIT_HOPE_DATE IS '방문 희망일시';
COMMENT ON COLUMN REQUEST.REQUEST_STATUS  IS '진행단계 - 접수완료/기사배정/방문예정/처리완료/취소';
COMMENT ON COLUMN REQUEST.STATUS          IS 'Y:정상 / N:삭제';

CREATE INDEX IDX_REQUEST_MEMBER ON REQUEST (MEMBER_NO);
CREATE INDEX IDX_REQUEST_STATUS ON REQUEST (REQUEST_STATUS);


/* =========================================================
   5. REQUEST_IMG  (접수 첨부 사진)
   ========================================================= */
CREATE TABLE REQUEST_IMG (
    IMG_NO       NUMBER         NOT NULL,
    REQUEST_NO   NUMBER         NOT NULL,
    ORIGIN_NAME  VARCHAR2(255)  NOT NULL,
    CHANGE_NAME  VARCHAR2(255)  NOT NULL,
    IMG_PATH     VARCHAR2(255)  NOT NULL,
    IMG_LEVEL    NUMBER         DEFAULT 1 NOT NULL,
    UPLOAD_DATE  DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_REQUEST_IMG  PRIMARY KEY (IMG_NO),
    CONSTRAINT FK_IMG_REQUEST  FOREIGN KEY (REQUEST_NO) REFERENCES REQUEST (REQUEST_NO) ON DELETE CASCADE,
    CONSTRAINT CK_IMG_LEVEL    CHECK (IMG_LEVEL >= 1)
);

COMMENT ON TABLE  REQUEST_IMG             IS '접수 첨부 사진';
COMMENT ON COLUMN REQUEST_IMG.ORIGIN_NAME IS '사용자가 올린 원본 파일명';
COMMENT ON COLUMN REQUEST_IMG.CHANGE_NAME IS '서버 저장용 변경 파일명';
COMMENT ON COLUMN REQUEST_IMG.IMG_LEVEL   IS '1:대표사진 / 2 이상:상세사진';


/* =========================================================
   6. ASSIGNMENT  (기사 배정)   REQUEST 1 : 1
   ========================================================= */
CREATE TABLE ASSIGNMENT (
    ASSIGN_NO    NUMBER         NOT NULL,
    REQUEST_NO   NUMBER         NOT NULL,
    ENGINEER_NO  NUMBER         NOT NULL,
    VISIT_DATE   DATE,
    ASSIGN_DATE  DATE           DEFAULT SYSDATE NOT NULL,
    ADMIN_MEMO   VARCHAR2(500),
    CONSTRAINT PK_ASSIGNMENT   PRIMARY KEY (ASSIGN_NO),
    CONSTRAINT UQ_ASSIGN_REQ   UNIQUE (REQUEST_NO),
    CONSTRAINT FK_ASG_REQUEST  FOREIGN KEY (REQUEST_NO)  REFERENCES REQUEST (REQUEST_NO) ON DELETE CASCADE,
    CONSTRAINT FK_ASG_ENGINEER FOREIGN KEY (ENGINEER_NO) REFERENCES ENGINEER (ENGINEER_NO)
);

COMMENT ON TABLE  ASSIGNMENT            IS '기사 배정 및 방문 일정';
COMMENT ON COLUMN ASSIGNMENT.VISIT_DATE IS '확정된 방문 일시';
COMMENT ON COLUMN ASSIGNMENT.ADMIN_MEMO IS '관리자 메모';


/* =========================================================
   7. REPAIR_RESULT  (처리 결과)   REQUEST 1 : 1
   ========================================================= */
CREATE TABLE REPAIR_RESULT (
    RESULT_NO       NUMBER          NOT NULL,
    REQUEST_NO      NUMBER          NOT NULL,
    RESULT_CONTENT  VARCHAR2(2000)  NOT NULL,
    USED_PART       VARCHAR2(300),
    COST            NUMBER          DEFAULT 0 NOT NULL,
    COMPLETE_DATE   DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_REPAIR_RESULT PRIMARY KEY (RESULT_NO),
    CONSTRAINT UQ_RESULT_REQ    UNIQUE (REQUEST_NO),
    CONSTRAINT FK_RST_REQUEST   FOREIGN KEY (REQUEST_NO) REFERENCES REQUEST (REQUEST_NO) ON DELETE CASCADE,
    CONSTRAINT CK_RESULT_COST   CHECK (COST >= 0)
);

COMMENT ON TABLE  REPAIR_RESULT           IS '수리 처리 결과';
COMMENT ON COLUMN REPAIR_RESULT.USED_PART IS '사용 부품';
COMMENT ON COLUMN REPAIR_RESULT.COST      IS '수리 비용 (원)';


/* =========================================================
   8. REPAIR_COMMENT  (접수 문의 댓글)
   ========================================================= */
CREATE TABLE REPAIR_COMMENT (
    COMMENT_NO       NUMBER          NOT NULL,
    REQUEST_NO       NUMBER          NOT NULL,
    MEMBER_NO        NUMBER          NOT NULL,
    COMMENT_CONTENT  VARCHAR2(1000)  NOT NULL,
    CREATE_DATE      DATE            DEFAULT SYSDATE NOT NULL,
    STATUS           CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_REPAIR_COMMENT PRIMARY KEY (COMMENT_NO),
    CONSTRAINT FK_CMT_REQUEST    FOREIGN KEY (REQUEST_NO) REFERENCES REQUEST (REQUEST_NO) ON DELETE CASCADE,
    CONSTRAINT FK_CMT_MEMBER     FOREIGN KEY (MEMBER_NO)  REFERENCES MEMBER (MEMBER_NO),
    CONSTRAINT CK_CMT_STATUS     CHECK (STATUS IN ('Y', 'N'))
);

COMMENT ON TABLE  REPAIR_COMMENT        IS '접수 문의 댓글';
COMMENT ON COLUMN REPAIR_COMMENT.STATUS IS 'Y:정상 / N:삭제';


/* =========================================================
   시퀀스
   ========================================================= */
CREATE SEQUENCE SEQ_MEMBER   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ENGINEER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REQUEST  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_IMG      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ASSIGN   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESULT   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMMENT  START WITH 1 INCREMENT BY 1 NOCACHE;


/* =========================================================
   기초 데이터
   ========================================================= */
INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, '냉장고');
INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, '세탁기');
INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, '에어컨');
INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, '보일러');
INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, 'TV/영상');
INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, '인터넷/통신');
INSERT INTO CATEGORY VALUES (SEQ_CATEGORY.NEXTVAL, '기타');

-- 관리자 계정 (비밀번호는 개발 시 암호화 값으로 교체)
INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, PHONE, MEMBER_ROLE)
VALUES (SEQ_MEMBER.NEXTVAL, 'admin', 'admin1234', '관리자', '02-0000-0000', 'A');

-- 테스트 회원
INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, PHONE, ADDRESS)
VALUES (SEQ_MEMBER.NEXTVAL, 'user01', 'user1234', '김테스트', '010-1111-2222', '서울시 강남구 테헤란로 1');

-- 수리기사
INSERT INTO ENGINEER (ENGINEER_NO, ENGINEER_NAME, CATEGORY_NO, PHONE, REGION)
VALUES (SEQ_ENGINEER.NEXTVAL, '박기사', 1, '010-3333-4444', '서울 강남');
INSERT INTO ENGINEER (ENGINEER_NO, ENGINEER_NAME, CATEGORY_NO, PHONE, REGION)
VALUES (SEQ_ENGINEER.NEXTVAL, '이기사', 3, '010-5555-6666', '서울 송파');
INSERT INTO ENGINEER (ENGINEER_NO, ENGINEER_NAME, CATEGORY_NO, PHONE, REGION)
VALUES (SEQ_ENGINEER.NEXTVAL, '최기사', 4, '010-7777-8888', '경기 성남');

COMMIT;


/* =========================================================
   자주 쓰게 될 조회 쿼리 (MyBatis 작성 시 참고)
   ========================================================= */

-- [1] 내 접수 목록 (페이징 전 기본형)
SELECT R.REQUEST_NO, R.REQUEST_TITLE, C.CATEGORY_NAME,
       R.REQUEST_STATUS, R.VISIT_HOPE_DATE, R.CREATE_DATE
  FROM REQUEST R
  JOIN CATEGORY C ON (R.CATEGORY_NO = C.CATEGORY_NO)
 WHERE R.MEMBER_NO = #{memberNo}
   AND R.STATUS = 'Y'
 ORDER BY R.REQUEST_NO DESC;

-- [2] 접수 상세 + 배정 + 결과 (진행단계 화면용)
SELECT R.REQUEST_NO, R.REQUEST_TITLE, R.SYMPTOM, R.REQUEST_STATUS,
       R.VISIT_ADDRESS, R.VISIT_HOPE_DATE,
       E.ENGINEER_NAME, E.PHONE AS ENGINEER_PHONE, A.VISIT_DATE,
       RS.RESULT_CONTENT, RS.COST, RS.COMPLETE_DATE
  FROM REQUEST R
  LEFT JOIN ASSIGNMENT    A  ON (R.REQUEST_NO = A.REQUEST_NO)
  LEFT JOIN ENGINEER      E  ON (A.ENGINEER_NO = E.ENGINEER_NO)
  LEFT JOIN REPAIR_RESULT RS ON (R.REQUEST_NO = RS.REQUEST_NO)
 WHERE R.REQUEST_NO = #{requestNo};

-- [3] 관리자 - 상태별 접수 현황 집계
SELECT REQUEST_STATUS, COUNT(*) AS CNT
  FROM REQUEST
 WHERE STATUS = 'Y'
 GROUP BY REQUEST_STATUS;

-- [4] 카테고리별 접수 건수 (통계 화면용)
SELECT C.CATEGORY_NAME, COUNT(R.REQUEST_NO) AS CNT
  FROM CATEGORY C
  LEFT JOIN REQUEST R ON (C.CATEGORY_NO = R.CATEGORY_NO AND R.STATUS = 'Y')
 GROUP BY C.CATEGORY_NAME
 ORDER BY CNT DESC;
