spring.application.name=fixer

server.port=8989

# JSP 화면 경로 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# DB 접속 정보
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##RR
spring.datasource.password=RR
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# MyBatis 설정
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.fixer.verify.model.dto
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.configuration.map-underscore-to-camel-case=true

# 파일 업로드 크기 제한
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# 파일 저장 경로 (직접 정한 값)
file.upload-dir=uploads
file.upload-dir.license=uploads/license