DROP TABLE FIXER_CATEGORY  CASCADE CONSTRAINTS;
DROP TABLE FIXER_REGION    CASCADE CONSTRAINTS;
DROP TABLE FIXER_LICENSE   CASCADE CONSTRAINTS;
DROP TABLE FIXER_PROFILE   CASCADE CONSTRAINTS;
DROP TABLE CATEGORY        CASCADE CONSTRAINTS;
DROP TABLE USERS           CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_USERS;
DROP SEQUENCE SEQ_FIXER_PROFILE;
DROP SEQUENCE SEQ_FIXER_LICENSE;
DROP SEQUENCE SEQ_FIXER_REGION;
DROP SEQUENCE SEQ_FIXER_CATEGORY;

--==================================================
-- F-14 기사 인증 신청 : 연습용 스키마
--==================================================

--------------------------------------------------
-- ① 테이블 생성
--------------------------------------------------
CREATE TABLE USERS (
    USER_ID          VARCHAR2(30)   NOT NULL,
    USER_NO          NUMBER,
    USER_PWD         VARCHAR2(100)  NOT NULL,
    USER_NAME        VARCHAR2(50)   NOT NULL,
    USER_PNUMBER     VARCHAR2(20),
    USER_EMAIL       VARCHAR2(100),
    USER_ROLE        VARCHAR2(10)   DEFAULT 'USER',
    ACCOUNT_STATUS   VARCHAR2(10)   DEFAULT 'NORMAL',
    USER_CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP,
    IS_WITHDRAWN     NUMBER(1)      DEFAULT 0,
    WITHDRAWN_AT     TIMESTAMP
);

CREATE TABLE CATEGORY (
    CATEGORY_ID    VARCHAR2(100)  NOT NULL,
    CATEGORY_NO    NUMBER         NOT NULL,
    CATEGORY_ITEM  VARCHAR2(100)  NOT NULL
);

CREATE TABLE FIXER_PROFILE (
    USER_ID              VARCHAR2(30)   NOT NULL,
    FIXER_NO             NUMBER         NOT NULL,
    FIXER_APPROVAL       VARCHAR2(20)   DEFAULT 'PENDING',
    FIXER_APPROVED_AT    TIMESTAMP,
    FIXER_REJECT_REASON  VARCHAR2(500),
    FIXER_INTRO          VARCHAR2(500),
    FIXER_CAREER         VARCHAR2(200)
);

CREATE TABLE FIXER_LICENSE (
    LICENSE_ID    NUMBER         NOT NULL,
    FIXER_ID      VARCHAR2(30)   NOT NULL,
    LICENSE_NAME  VARCHAR2(100)  NOT NULL,
    LICENSE_NO    VARCHAR2(100),
    LICENSE_FILE  VARCHAR2(500)  NOT NULL,
    ISSUED_AT     DATE,
    UPLOADED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE TABLE FIXER_REGION (
    FIXER_REGION_ID  NUMBER         NOT NULL,
    FIXER_ID         VARCHAR2(30)   NOT NULL,
    REGION_NAME      VARCHAR2(100)  NOT NULL
);

CREATE TABLE FIXER_CATEGORY (
    FIXER_CATEGORY_ID  NUMBER         NOT NULL,
    FIXER_ID           VARCHAR2(30)   NOT NULL,
    CATEGORY_ID        VARCHAR2(100)  NOT NULL
);

--------------------------------------------------
-- ② 기본키(PK)
--------------------------------------------------
ALTER TABLE USERS          ADD CONSTRAINT PK_USERS          PRIMARY KEY (USER_ID);
ALTER TABLE CATEGORY       ADD CONSTRAINT PK_CATEGORY       PRIMARY KEY (CATEGORY_ID);
ALTER TABLE FIXER_PROFILE  ADD CONSTRAINT PK_FIXER_PROFILE  PRIMARY KEY (USER_ID);
ALTER TABLE FIXER_LICENSE  ADD CONSTRAINT PK_FIXER_LICENSE  PRIMARY KEY (LICENSE_ID);
ALTER TABLE FIXER_REGION   ADD CONSTRAINT PK_FIXER_REGION   PRIMARY KEY (FIXER_REGION_ID);
ALTER TABLE FIXER_CATEGORY ADD CONSTRAINT PK_FIXER_CATEGORY PRIMARY KEY (FIXER_CATEGORY_ID);

--------------------------------------------------
-- ③ 외래키(FK) + 상태값 체크
--------------------------------------------------
ALTER TABLE FIXER_PROFILE ADD CONSTRAINT FK_FIXER_PROFILE_USERS
      FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE FIXER_LICENSE ADD CONSTRAINT FK_FIXER_LICENSE_PROFILE
      FOREIGN KEY (FIXER_ID) REFERENCES FIXER_PROFILE(USER_ID) ON DELETE CASCADE;

ALTER TABLE FIXER_REGION ADD CONSTRAINT FK_FIXER_REGION_PROFILE
      FOREIGN KEY (FIXER_ID) REFERENCES FIXER_PROFILE(USER_ID) ON DELETE CASCADE;

ALTER TABLE FIXER_CATEGORY ADD CONSTRAINT FK_FIXER_CATEGORY_PROFILE
      FOREIGN KEY (FIXER_ID) REFERENCES FIXER_PROFILE(USER_ID) ON DELETE CASCADE;

ALTER TABLE FIXER_CATEGORY ADD CONSTRAINT FK_FIXER_CATEGORY_CATEGORY
      FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

ALTER TABLE FIXER_PROFILE ADD CONSTRAINT CK_FIXER_APPROVAL
      CHECK (FIXER_APPROVAL IN ('PENDING', 'APPROVED', 'REJECTED'));

--------------------------------------------------
-- ④ 시퀀스
--------------------------------------------------
CREATE SEQUENCE SEQ_USERS          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FIXER_PROFILE  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FIXER_LICENSE  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FIXER_REGION   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FIXER_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

--------------------------------------------------
-- ⑤ 기초 데이터 : 카테고리
--------------------------------------------------
INSERT INTO CATEGORY VALUES ('PC',        1, '컴퓨터/노트북');
INSERT INTO CATEGORY VALUES ('MOBILE',    2, '휴대폰/태블릿');
INSERT INTO CATEGORY VALUES ('APPLIANCE', 3, '가전제품');
INSERT INTO CATEGORY VALUES ('FURNITURE', 4, '가구/조립');
INSERT INTO CATEGORY VALUES ('ELECTRIC',  5, '전기/조명');

--------------------------------------------------
-- ⑥ 기초 데이터 : 테스트 회원
--------------------------------------------------
INSERT INTO USERS (USER_ID, USER_NO, USER_PWD, USER_NAME, USER_PNUMBER, USER_ROLE)
VALUES ('fixer01', SEQ_USERS.NEXTVAL, '1234', '김기사', '010-1111-1111', 'FIXER');

INSERT INTO USERS (USER_ID, USER_NO, USER_PWD, USER_NAME, USER_PNUMBER, USER_ROLE)
VALUES ('fixer02', SEQ_USERS.NEXTVAL, '1234', '이기사', '010-2222-2222', 'FIXER');

INSERT INTO USERS (USER_ID, USER_NO, USER_PWD, USER_NAME, USER_PNUMBER, USER_ROLE)
VALUES ('user01',  SEQ_USERS.NEXTVAL, '1234', '박고객', '010-3333-3333', 'USER');

COMMIT;
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;
SELECT SEQUENCE_NAME FROM USER_SEQUENCES ORDER BY SEQUENCE_NAME;
SELECT * FROM CATEGORY;
SELECT USER_ID, USER_NAME, USER_ROLE FROM USERS;